config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages do
    post :sort, on: :collection
    resources :sections, controller: 'pages/sections' do
      post :sort, on: :collection
    end
  end
  resources :workspaces do
    get :switch_to, on: :member
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create', as: :create_user
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create', as: :createsession
  delete 'logout', to: 'sessions#destroy', as: :logout
  root 'pages#index'
  get 'home', to: 'home#index'
end

app/models/workspace.rb
# frozen_string_literal: true

class Workspace < ApplicationRecord
  belongs_to :user
  has_many :pages, dependent: :destroy
  validates :title, presence: true
end

app/controllers/workspaces_controller.rb
# frozen_string_literal: true

class WorkspacesController < ApplicationController
  before_action :set_workspace, only: %i[show edit update destroy switch_to]

  # GET /workspaces or /workspaces.json
  def index
    @workspaces = Workspace.all
  end

  def switch_to
    self.current_workspace = @workspace
    redirect_to root_path
  end

  # GET /workspaces/1 or /workspaces/1.json
  def show; end

  # GET /workspaces/new
  def new
    @workspace = Workspace.new
  end

  # GET /workspaces/1/edit
  def edit; end

  # POST /workspaces or /workspaces.json
  def create
    @workspace = Workspace.new(workspace_params)
    @workspace.user = Current.user
    respond_to do |format|
      if @workspace.save
        handle_successful_creation(format)
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workspaces/1 or /workspaces/1.json
  def update
    respond_to do |format|
      if @workspace.update(workspace_params)
        format.html { redirect_to root_path, notice: 'Workspace was successfully updated.', status: :see_other }
        format.json { render :show, status: :ok, location: @workspace }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workspaces/1 or /workspaces/1.json
  def destroy
    @workspace.destroy!

    respond_to do |format|
      format.html { redirect_to workspaces_path, notice: 'Workspace was successfully destroyed.', status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def handle_successful_creation(format)
    self.current_workspace = @workspace
    format.html { redirect_to root_url, notice: 'Workspace was successfully created.' }
    format.json { render :show, status: :created, location: @workspace }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_workspace
    @workspace = Current.user.workspaces.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def workspace_params
    params.expect(workspace: %i[user_id title])
  end
end

app/helpers/workspaces_helper.rb
# frozen_string_literal: true

module WorkspacesHelper
end

app/views/workspaces/_form.html.slim
= form_with(model: workspace, data: { turbo_frame: '_top' }) do |form|
  = form.text_field :title, class: "pr-7 font-semibold py-3", autofocus: true, onfocus: "this.select()"

app/views/workspaces/_workspace.html.slim
div id="#{dom_id workspace}"
  p
    strong User:
    =< workspace.user_id

app/views/workspaces/edit.html.slim
= turbo_frame_tag "workspace" do
  == render "form", workspace: @workspace

app/views/workspaces/index.html.slim
p style="color: green" = notice

h1 Workspaces

#workspaces
  - @workspaces.each do |workspace|
    == render workspace
    p
      = link_to "Show this workspace", workspace

= link_to "New workspace", new_workspace_path

app/views/workspaces/new.html.slim
h1 New workspace

== render "form", workspace: @workspace

br

div
  = link_to "Back to workspaces", workspaces_path

app/views/workspaces/show.html.slim
p style="color: green" = notice

== render @workspace

div
  => link_to "Edit this workspace", edit_workspace_path(@workspace)
  '|
  =< link_to "Back to workspaces", workspaces_path

  = button_to "Destroy this workspace", @workspace, method: :delete