config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages do
    post :sort, on: :collection
    resources :sections, controller: 'pages/sections' do
      post :sort, on: :collection
    end
  end
  resources :workspaces do
    get :switch_to, on: :member
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create', as: :create_user
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create', as: :createsession
  delete 'logout', to: 'sessions#destroy', as: :logout
  root 'pages#index'
  get 'home', to: 'home#index'
end

app/views/pages/_form.html.slim
= form_with(model: page, data: { turbo_frame: '_top' }) do |form|
  div
    = form.text_field :title, palceholder: "Page title", class: 'h2 text-center -my-2', autofocus: true, onfocus: "this.select()"

app/views/pages/_page.html.slim
.page-container(data-sortable-id="#{page.id}")
  div class="item group/link px-1"
    .row.space-x-2.text-sm
      = link_to page, class: 'clean row space-x-2 flex-1 page-link' do
        = t_icon page.frontpage? ? 'home' : 'file-description', size: 20
        span = truncate page.d_title, length: 14
      = button_to pages_path(parent_id: page.id), class: 'clean btn p-1 invisible group-hover/link:visible' do
        = t_icon 'plus', size: 20
  .children.pl-4.nested-sortable
    = render page.children.order(:position)

app/views/pages/edit.html.slim
= turbo_frame_tag 'page' do
  == render "form", page: @page

app/views/pages/index.html.slim
p style="color: green" = notice

.text-center.p-10
  h3 Good Evening, #{Current.user.email}

.mx-auto class="w-[850px]"
  .grid.grid-cols-4.gap-4
    - Current.workspace.pages.limit(8).each_slice(4) do |pages|
      - pages.each do |page|
        = link_to page, class: 'pages border rounded-2xl clean'
          .head.bg-stone-100.h-12.rounded-t-2xl
          .-mt-4.px-4
            = t_icon 'file-description', css_classes: 'text-gray-400', size: 30
          .p-5.title = page.d_title

app/views/pages/new.html.slim
h1 New page

== render "form", page: @page

br

div
  = link_to "Back to pages", pages_path

app/views/pages/show.html.slim
p style="color: green" = notice
.text-center.p-10.max-w-3xl.mx-auto.container
  = turbo_frame_tag 'page' do
    = link_to @page.d_title, edit_page_path(@page), class: 'h2 clean'
    .text-sm = SecureRandom.urlsafe_base64
    .row.justify-center
      - unless @page.frontpage
        = button_to [@page, page: { frontpage: true }], method: :patch, class: 'clean' do
          = t_icon :home
      = button_to "Destroy this page", @page, method: :delete, class: 'danger'

.max-auto class="w-[80%]"
  .page-sections.col.space-y-8 data-controller="sortable" data-sortable-url-value="#{sort_page_sections_path(@page)}"
    = render partial: 'pages/sections/section', collection: @page.sections

  = button_to "Text", page_sections_path(@page, section: { kind: 'text' }), class: 'btn'