config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages do
    post :sort, on: :collection
    resources :sections, controller: 'pages/sections' do
      post :sort, on: :collection
    end
  end
  resources :workspaces do
    get :switch_to, on: :member
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'sign_up', to: 'users#create', as: :create_user
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create', as: :createsession
  delete 'logout', to: 'sessions#destroy', as: :logout
  root 'pages#index'
  get 'home', to: 'home#index'
end

app/views/layouts/application.html.slim
doctype html
html.h-full

  head
    title = content_for(:title) || "Notion Copy" 
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head


    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"

    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags

  body.h-full
    = yield(:main).presence || yield

app/views/layouts/pages.html.slim
= content_for :main do
  .flex.h-full
    .leftcol.bg-stone-100.flex.flex-col class="w-[240px]"
      = turbo_frame_tag "workspace", class: "flex space-x-2"
        = render layout: 'dropdown', locals: { button_classes: 'clean px-1 py-2 hover:bg-gray-200 rounded', surface_css: 'mx-1 left-0 bg-white drop-shadow-xl' } do
          .flex.flex-col
            - Current.user.workspaces.each do |workspace|
              = link_to truncate(workspace.title, length: 20), switch_to_workspace_path(workspace), class: 'clean px-3 py-2 hover:bg-gray-200', data: { turbo_frame: '_top'}
            = button_to "New workspace", workspaces_path(workspace: { title: "Workspace: #{Current.user.workspaces.count + 1 }"}), class: 'clean px-3 py-2 hover:bg-gray-200'

        = link_to truncate(Current.workspace.title, length: 20), edit_workspace_path(Current.workspace), class: 'clean font-semibold px-3 py-2'
        .flex-1
      .flex-1
        = link_to root_url, class: 'clean page-link flex items-center space-x-2' do
          = t_icon 'home', size: 20
          span Home
        #pages.sortable(data-controller="nested-sortable" data-nested-sortable-target="root" data-nested-sortable-sort-url-value="#{sort_pages_path}")
          .nested-sortable
            = render Current.workspace.pages.roots.order(:position)
        .m-2 = button_to "New page", pages_path, class: 'w- full px-3 py-2 hover:bg-gray-200'
      .flex-1
      = button_to logout_path, method: :delete, class: 'w-full flex space-x-2 items-center justify-center hover:bg-stone-200 px-3 py-2' do
        span Logout
        = t_icon 'logout', size: 23
    .flex-1
      = yield

= render template: 'layouts/application'

app/views/layouts/sessions.html.slim
= content_for :main do
  .mx-auto.max-w-screen-sm.py-20 class="w-[450px]"
    = yield

= render template: 'layouts/application'